site_name: PinnFlow Documentation

theme:
  name: "readthedocs"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder

nav:
  - Index: index.md